In [1]:
import polars as pl
import os
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [17]:
log_softmax = nn.LogSoftmax(dim=1)
loss_fn = nn.NLLLoss()
# input to NLLLoss is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target must have 0 <= value < C
target = torch.tensor([1, 0, 4])
loss = loss_fn(log_softmax(input), target)
loss.backward()


In [18]:
input

tensor([[-2.2292, -2.0338, -0.2379,  1.6551, -1.7740],
        [-0.6900,  1.3315,  1.3086, -0.6436, -1.3100],
        [ 0.5042, -0.2538, -0.6092,  0.6722,  1.4927]], requires_grad=True)

In [19]:
target

tensor([1, 0, 4])

In [20]:
log_softmax(input)

tensor([[-4.0901, -3.8947, -2.0988, -0.2059, -3.6349],
        [-2.8630, -0.8415, -0.8644, -2.8166, -3.4830],
        [-1.7347, -2.4927, -2.8481, -1.5667, -0.7462]],
       grad_fn=<LogSoftmaxBackward0>)

In [21]:
loss

tensor(2.5013, grad_fn=<NllLossBackward0>)

In [22]:
# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss_fn = nn.NLLLoss()
data = torch.randn(N, 16, 10, 10)
conv = nn.Conv2d(16, C, (3, 3))
log_softmax = nn.LogSoftmax(dim=1)
# output of conv forward is of shape [N, C, 8, 8]
output = log_softmax(conv(data))
# each element in target must have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
# input to NLLLoss is of size N x C x height (8) x width (8)
loss = loss_fn(output, target)
loss.backward()